
from smart_data import SmartData
from typing import Dict, List, Tuple, Optional, Any 
from langchain_core.tools import StructuredTool, Tool

class SmartDataTools:

    def __init__(self, data:SmartData):
        self._data = data 

    # ----------------------------------------
    def emit_step_by_step_plan(self, step_by_step_plan: str) -> str:
        """
        Record and display the execution plan generated by the agent.
        """
        return step_by_step_plan

    def catalog_snapshot(self):
        """Returns schema and table descriptions for all tables in the database"""
        return self._data.catalog_snapshot()

    def get_table_names( self ):
        """Returns the table names"""
        return  self._data.get_table_names() 
    
    def get_tables_creation_datetime( self )-> Dict[str,str]  :
        """Returns the creation date of each table"""
        return self._data.get_tables_creation_datetime()
        
    def get_tables_brief_description( self ):
        """Returns a brief textual description of the tables"""
        return self._data.get_tables_brief_description() 

    def get_tools(self):
        tools = []
        for name in dir(self):
            if name.startswith("_") or name == "get_tools":
                continue
                
            attr = getattr(self, name)
            if not attr.__doc__:
                continue 


            if callable(attr) and attr.__doc__:
                tools.append(
                    StructuredTool.from_function(
                        func=attr,
                        name=name,
                        description=attr.__doc__,
                    )
                )
        return tools

    def sql_materialize( self, sql:str, materialized_table_name:str, table_description:str ):
        """
        materialize a table by executing sql and stores it in the database as a 'derived' table.  
        Args:
            sql(str): sql query to execute. Must start with WITH or SELECT 
            materialized_table_name: name given to the new table. 
            table_description: brief description of the resulting table  

        Returns:
            Message indicating that the table was generated and stored or a message indicating failure when an error occured
            This tool will  never return a table 
        """
        print('materializing')
        print('sql:',sql)
        print('description', table_description)

        retries = 0 

        try:
            df_result = self._data.execute_sql(sql, table_description)
            self._data.register_derived_table( df_result, materialized_table_name, table_description)
        
            return f"Observation: table {materialized_table_name} created "
        except Exception as e:

        
            return "SQL instruction failed" 

    def _reuse_table(self, table_name:str,table_description:str):
        """Call this function when a table can be reused"""

        return f"Table {table_name} is available to reuse:\ndeescription: {table_description} "

