



def format_label(name: str) -> str:
    """
    Convert column-like names to display labels.

    Examples:
    - year_quarter -> Year quarter
    - percentage_contribution -> Percentage contribution
    - TOTAL_WATER_INJECTION_VOLUME -> Total water injection volume
    """
    if name is None:
        return ""

    text = str(name).replace("_", " ").strip().lower()
    return text[:1].upper() + text[1:]

def _as_list(value):
    if value is None:
        return []
    return [value] if isinstance(value, str) else list(value)


def _validate_columns(
    df: pd.DataFrame,
    columns: list[str],
    label: str = "column",
):
    """
    Validate that all requested columns exist in the dataframe.
    """

    missing = [c for c in columns if c not in df.columns]

    if missing:
        raise ValueError(f"Missing {label}(s): {missing}")

def _filter_args(
    tool: str,
    args: dict[str, Any],
) -> dict[str, Any]:
    """
    Remove unsupported arguments generated by the LLM.
    """

    allowed_args = {
        "preprocess_for_chart": {
            "create_combined_category",
            "create_date_bucket",
        },

        "plot_bar_chart": {
            "x",
            "y",
            "aggregate",
            "group_by",
            "color_by",
            "orientation",
            "barmode",
            "title",
            "template",
        },

        "plot_line_chart": {
            "x",
            "y",
            "aggregate",
            "group_by",
            "color_by",
            "date_bucket",
            "cumulative",
            "title",
            "template",
        },

        "plot_pie_chart": {
            "labels",
            "values",
            "aggregate",
            "group_by",
            "title",
            "hole",
            "template",
        },

        "plot_scatter_chart": {
            "x",
            "y",
            "color_by",
            "size_by",
            "text_by",
            "title",
            "template",
        },
        "plot_list": {
                    "columns", "title",
                },

    }

    if tool not in allowed_args:
        raise ValueError(f"Unknown tool: {tool}")

    return {
        k: v
        for k, v in args.items()
        if k in allowed_args[tool]
    }

ALLOWED_AGGS = {"sum", "mean", "median", "min", "max", "count", "nunique"}

def _aggregate(
    df: pd.DataFrame,
    group_by: list[str],
    value_cols: list[str],
    aggregate: str,
) -> pd.DataFrame:
    if aggregate not in ALLOWED_AGGS:
        raise ValueError(f"Unsupported aggregate: {aggregate}")

    _validate_columns(df, group_by, "group_by column")
    _validate_columns(df, value_cols, "value column")

    return (
        df.groupby(group_by, dropna=False, as_index=False)[value_cols]
        .agg(aggregate)
    )

def _bucket_date(
    df: pd.DataFrame,
    date_col: str,
    bucket: str,
) -> tuple[pd.DataFrame, str]:
    """
    Create a date bucket column.

    bucket:
    - "D": day
    - "W": week
    - "M": month
    - "Q": quarter
    - "Y": year
    """

    out = df.copy()
    bucket_col = f"{date_col}_{bucket}"

    _validate_columns(out, [date_col])

    out[date_col] = pd.to_datetime(out[date_col], errors="coerce")

    if bucket == "D":
        out[bucket_col] = out[date_col].dt.to_period("D").dt.to_timestamp()
    elif bucket == "W":
        out[bucket_col] = out[date_col].dt.to_period("W").dt.start_time
    elif bucket == "M":
        out[bucket_col] = out[date_col].dt.to_period("M").dt.to_timestamp()
    elif bucket == "Q":
        out[bucket_col] = out[date_col].dt.to_period("Q").dt.to_timestamp()
    elif bucket == "Y":
        out[bucket_col] = out[date_col].dt.to_period("Y").dt.to_timestamp()
    else:
        raise ValueError("date_bucket must be one of: D, W, M, Q, Y")

    return out, bucket_col

def preprocess_for_chart(
    df: pd.DataFrame,
    *,
    create_combined_category: dict | None = None,
    create_date_bucket: dict | None = None,
) -> pd.DataFrame:
    """
    Prepare a dataframe for charting by creating optional derived columns.
    """

    out = df.copy()

    if create_combined_category:
        col1 = create_combined_category["col1"]
        col2 = create_combined_category["col2"]
        new_col = create_combined_category.get("new_col") or f"{col1}_{col2}"
        sep = create_combined_category.get("sep", " / ")

        _validate_columns(out, [col1, col2])

        out[new_col] = (
            out[col1].fillna("").astype(str)
            + sep
            + out[col2].fillna("").astype(str)
        )

    if create_date_bucket:
        date_col = create_date_bucket["date_col"]
        bucket = create_date_bucket["bucket"]
        new_col = create_date_bucket.get("new_col") or f"{date_col}_{bucket}"

        _validate_columns(out, [date_col])

        dt = pd.to_datetime(out[date_col], errors="coerce")

        if bucket == "D":
            out[new_col] = dt.dt.to_period("D").dt.to_timestamp()
        elif bucket == "W":
            out[new_col] = dt.dt.to_period("W").dt.start_time
        elif bucket == "M":
            out[new_col] = dt.dt.to_period("M").dt.to_timestamp()
        elif bucket == "Q":
            out[new_col] = dt.dt.to_period("Q").dt.to_timestamp()
        elif bucket == "Y":
            out[new_col] = dt.dt.to_period("Y").dt.to_timestamp()
        else:
            raise ValueError("bucket must be one of: D, W, M, Q, Y")

    return out

def plot_bar_chart(
    df: pd.DataFrame,
    x: str,
    y: str | list[str],
    *,
    aggregate: str | None = None,
    group_by: list[str] | str | None = None,
    color_by: str | None = None,
    orientation: str = "v",
    barmode: str = "group",
    title: str | None = None,
    #template: str = "plotly_white",
) -> dict:
    y_cols = _as_list(y)

    required = [x, *y_cols]
    if color_by:
        required.append(color_by)

    _validate_columns(df, required)

    work = df.copy()

    if aggregate is not None:
        group_cols = _as_list(group_by) or [x]

        if x not in group_cols:
            group_cols.insert(0, x)

        if color_by and color_by not in group_cols:
            group_cols.append(color_by)

        work = _aggregate(work, group_cols, y_cols, aggregate)

    data = []
    groups = work.groupby(color_by, dropna=False) if color_by else [(None, work)]

    for group_value, g in groups:
        for y_col in y_cols:
            if group_value is None:
                name = format_label(y_col)
            else:
                name = format_label(str(group_value))

            if group_value is not None and len(y_cols) > 1:
                name = f"{format_label(str(group_value))} - {format_label(y_col)}"

            trace = {
                "type": "bar",
                "name": name,
                "orientation": orientation,
            }

            if orientation == "h":
                trace["x"] = g[y_col].tolist()
                trace["y"] = g[x].astype(str).tolist()
            else:
                trace["x"] = g[x].astype(str).tolist()
                trace["y"] = g[y_col].tolist()

            data.append(trace)

    y_label = format_label(", ".join(y_cols))
    x_label = format_label(x)

    return {
        "data": data,
        "layout": {
            "title": {
                "text": title or f"{y_label} by {x_label}"
            },
            "xaxis": {
                "title": {
                    "text": y_label if orientation == "h" else x_label
                }
            },
            "yaxis": {
                "title": {
                    "text": x_label if orientation == "h" else y_label
                }
            },
            "barmode": barmode,
            #"template": template,
        },
        "config": {
            "responsive": True,
            "displaylogo": False,
        },
    }

def plot_line_chart(
    df: pd.DataFrame,
    x: str,
    y: str | list[str],
    *,
    aggregate: str | None = None,
    group_by: list[str] | str | None = None,
    color_by: str | None = None,
    date_bucket: str | None = None,
    cumulative: bool = False,
    title: str | None = None,
    #template: str = "plotly_white",
) -> dict:
    y_cols = _as_list(y)

    required = [x, *y_cols]
    if color_by:
        required.append(color_by)

    _validate_columns(df, required)

    work = df.copy()
    x_plot = x

    if date_bucket is not None:
        work, x_plot = _bucket_date(work, x, date_bucket)

    if aggregate is not None:
        group_cols = _as_list(group_by) or [x_plot]

        if x_plot not in group_cols:
            group_cols.insert(0, x_plot)

        if color_by and color_by not in group_cols:
            group_cols.append(color_by)

        work = _aggregate(work, group_cols, y_cols, aggregate)

    sort_cols = [color_by, x_plot] if color_by else [x_plot]
    work = work.sort_values(sort_cols)

    if cumulative:
        if color_by:
            for col in y_cols:
                work[col] = work.groupby(color_by, dropna=False)[col].cumsum()
        else:
            for col in y_cols:
                work[col] = work[col].cumsum()

    data = []
    groups = work.groupby(color_by, dropna=False) if color_by else [(None, work)]

    
    total_points = len(work) * len(y_cols)
    disable_all_markers = total_points > 2000


    for group_value, g in groups:
        for y_col in y_cols:
            name = y_col if group_value is None else str(group_value)

            if group_value is not None and len(y_cols) > 1:
                name = f"{group_value} - {y_col}"

            name = format_label(y_col)


            n_points = len(g)

            use_markers = (
                not disable_all_markers
                and n_points <= 100
            )

            mode = "lines"##"lines+markers" if use_markers else "lines"


            data.append({
                "type": "scatter",
                "mode": mode,#"lines+markers",
                "x": g[x_plot].tolist(),
                "y": g[y_col].tolist(),
                "name": name,
            })


 
    return {
        "data": data,
        "layout": {
            "title": {"text": format_label(title) or f"{', '.join(y_cols)} over {x}"},
            "xaxis": {"title": {"text": format_label(x)}},
            "yaxis": {"title": {"text":  format_label(", ".join(y_cols))   }},
            #"template": template,
        },
        "config": {
            "responsive": True,
            "displaylogo": False,
        },
    }

def plot_pie_chart(
    df: pd.DataFrame,
    labels: str,
    values: str,
    *,
    aggregate: str | None = None,
    group_by: list[str] | str | None = None,
    title: str | None = None,
    hole: float = 0.0,
    #template: str = "plotly_white",
) -> dict:
    _validate_columns(df, [labels, values])

    work = df.copy()

    if aggregate is not None:
        group_cols = _as_list(group_by) or [labels]

        if labels not in group_cols:
            group_cols.insert(0, labels)

        work = _aggregate(work, group_cols, [values], aggregate)

    return {
        "data": [
            {
                "type": "pie",
                "labels": work[labels].astype(str).tolist(),
                "values": work[values].tolist(),
                "hole": hole,
            }
        ],
        "layout": {
            "title": {"text": title or f"{values} share by {labels}"},
            #"template": template,
        },
        "config": {
            "responsive": True,
            "displaylogo": False,
        },
    }

def plot_scatter_chart(
    df: pd.DataFrame,
    x: str,
    y: str | list[str],
    *,
    color_by: str | None = None,
    size_by: str | None = None,
    text_by: str | None = None,
    title: str | None = None,
    #template: str = "plotly_white",
) -> dict:
    y_cols = _as_list(y)

    required = [x, *y_cols]
    if color_by:
        required.append(color_by)
    if size_by:
        required.append(size_by)
    if text_by:
        required.append(text_by)

    _validate_columns(df, required)

    work = df.copy()
    data = []
    groups = work.groupby(color_by, dropna=False) if color_by else [(None, work)]


    total_points = len(work) * len(y_cols)
    disable_all_markers = total_points > 2000


    for group_value, g in groups:
        for y_col in y_cols:
            name = y_col if group_value is None else str(group_value)

            if group_value is not None and len(y_cols) > 1:
                name = f"{group_value} - {y_col}"




            n_points = len(g)

            use_markers = (
                not disable_all_markers
                and n_points <= 100
            )

            mode = "markers" if use_markers else "lines"


            trace = {
                "type": "scattergl",
                "mode": mode,
                "x": g[x].tolist(),
                "y": g[y_col].tolist(),
                "name": name,
            }

            if size_by:
                size_values = pd.to_numeric(g[size_by], errors="coerce").fillna(0)
                max_size = max(float(size_values.max()), 1.0)

                trace["marker"] = {
                    "size": size_values.tolist(),
                    "sizemode": "area",
                    "sizeref": max_size / 40,
                    "sizemin": 4,
                }

            if text_by:
                trace["text"] = g[text_by].astype(str).tolist()
                trace["hovertemplate"] = (
                    f"{x}: %{{x}}<br>"
                    f"{y_col}: %{{y}}<br>"
                    f"{text_by}: %{{text}}"
                    "<extra></extra>"
                )

            data.append(trace)

    return {
        "data": data,
        "layout": {
            "title": {"text": title or f"{', '.join(y_cols)} vs {x}"},
            "xaxis": {"title": {"text": x}},
            "yaxis": {"title": {"text": ", ".join(y_cols)}},
            #"template": template,
        },
        "config": {
            "responsive": True,
            "displaylogo": False,
        },
    }

def plot_list(
    df: pd.DataFrame,
    columns: list[str] | str | None = None,
    *,
    sort_by: str | None = None,
    sort_order: str = "desc",
    limit: int | None = None,
    title: str | None = None,
) -> dict:
    work = df.copy()

    if columns is not None:
        columns = _as_list(columns)
        _validate_columns(work, columns)
        work = work[columns]

    if sort_by is not None:
        _validate_columns(work, [sort_by])

        ascending = sort_order.lower() == "asc"
        work = work.sort_values(sort_by, ascending=ascending)

    if limit is not None:
        work = work.head(limit)

    header_values = [format_label(c) for c in work.columns]

    cell_values = []
    for col in work.columns:
        s = work[col]

        if pd.api.types.is_datetime64_any_dtype(s):
            values = s.dt.strftime("%Y-%m-%d").fillna("").tolist()
        else:
            values = s.fillna("").astype(str).tolist()

        cell_values.append(values)

    return {
        "data": [
            {
                "type": "table",
                "header": {
                    "values": header_values,
                    "align": "left",
                },
                "cells": {
                    "values": cell_values,
                    "align": "left",
                },
            }
        ],
        "layout": {
            "title": {
                "text": format_label(title) or "Table"
            },
        },
        "config": {
            "responsive": True,
            "displaylogo": False,
        },
    }


